// Generated by scripts/gen_parameters.mjs from parameters.js. Do not edit.
export interface ParameterDefinition {
  readonly id: number;
  /** Value applied for this field when a preset omits it. */
  readonly default: number;
  readonly min: number;
  readonly max: number;
  readonly step: number;
  readonly unit: string;
  readonly values?: Readonly<Record<string, number>>;
  /** Preferred playground ceiling; the control expands for a preset above it. */
  readonly editorMax?: number;
}

export declare const ALGORITHM: { readonly mod1: 0; readonly mod2: 1; readonly stack2: 2; readonly feedback: 3; };
export declare const RATIOS: {
  readonly half: 0.5;
  readonly one: 1;
  readonly fourteen: 1.4;
  readonly fifteen: 1.5;
  readonly two: 2;
  readonly three: 3;
  readonly four: 4;
  readonly five: 5;
  readonly six: 6;
  readonly seven: 7;
  readonly eight: 8;
};

export declare const PARAMETERS: {
  readonly algorithm: { readonly id: 0; readonly default: 0; readonly min: 0; readonly max: 3; readonly step: 1; readonly unit: "enum"; readonly values: { readonly mod1: 0; readonly mod2: 1; readonly stack2: 2; readonly feedback: 3; }; };
  readonly index: { readonly id: 1; readonly default: 0.5; readonly min: 0; readonly max: 2; readonly step: 0.01; readonly unit: "ratio"; readonly editorMax: 1; };
  readonly feedback: { readonly id: 2; readonly default: 0; readonly min: 0; readonly max: 0.9; readonly step: 0.01; readonly unit: "ratio"; };
  readonly velToIndex: { readonly id: 3; readonly default: 0.3; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly gain: { readonly id: 4; readonly default: 0.32; readonly min: 0; readonly max: 0.85; readonly step: 0.01; readonly unit: "linear gain"; readonly editorMax: 0.8; };
  readonly op1Ratio: { readonly id: 5; readonly default: 1; readonly min: 0.5; readonly max: 8; readonly step: 0.1; readonly unit: "ratio"; readonly editorMax: 4; };
  readonly op1Level: { readonly id: 6; readonly default: 0.7; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "linear gain"; };
  readonly op1Attack: { readonly id: 7; readonly default: 0.005; readonly min: 0.001; readonly max: 2; readonly step: 0.001; readonly unit: "seconds"; };
  readonly op1Decay: { readonly id: 8; readonly default: 0.3; readonly min: 0.005; readonly max: 2; readonly step: 0.005; readonly unit: "seconds"; };
  readonly op1Sustain: { readonly id: 9; readonly default: 0.5; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly op1Release: { readonly id: 10; readonly default: 0.2; readonly min: 0.005; readonly max: 3; readonly step: 0.005; readonly unit: "seconds"; };
  readonly op2Ratio: { readonly id: 11; readonly default: 2; readonly min: 0.5; readonly max: 8; readonly step: 0.1; readonly unit: "ratio"; readonly editorMax: 4; };
  readonly op2Level: { readonly id: 12; readonly default: 0.6; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "linear gain"; };
  readonly op2Attack: { readonly id: 13; readonly default: 0.005; readonly min: 0.001; readonly max: 2; readonly step: 0.001; readonly unit: "seconds"; };
  readonly op2Decay: { readonly id: 14; readonly default: 0.3; readonly min: 0.005; readonly max: 2; readonly step: 0.005; readonly unit: "seconds"; };
  readonly op2Sustain: { readonly id: 15; readonly default: 0.5; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly op2Release: { readonly id: 16; readonly default: 0.2; readonly min: 0.005; readonly max: 3; readonly step: 0.005; readonly unit: "seconds"; };
  readonly op3Ratio: { readonly id: 17; readonly default: 3; readonly min: 0.5; readonly max: 8; readonly step: 0.1; readonly unit: "ratio"; readonly editorMax: 4; };
  readonly op3Level: { readonly id: 18; readonly default: 0.5; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "linear gain"; };
  readonly op3Attack: { readonly id: 19; readonly default: 0.005; readonly min: 0.001; readonly max: 2; readonly step: 0.001; readonly unit: "seconds"; };
  readonly op3Decay: { readonly id: 20; readonly default: 0.3; readonly min: 0.005; readonly max: 2; readonly step: 0.005; readonly unit: "seconds"; };
  readonly op3Sustain: { readonly id: 21; readonly default: 0.5; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly op3Release: { readonly id: 22; readonly default: 0.2; readonly min: 0.005; readonly max: 3; readonly step: 0.005; readonly unit: "seconds"; };
  readonly op4Ratio: { readonly id: 23; readonly default: 4; readonly min: 0.5; readonly max: 8; readonly step: 0.1; readonly unit: "ratio"; readonly editorMax: 4; };
  readonly op4Level: { readonly id: 24; readonly default: 0.5; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "linear gain"; };
  readonly op4Attack: { readonly id: 25; readonly default: 0.005; readonly min: 0.001; readonly max: 2; readonly step: 0.001; readonly unit: "seconds"; };
  readonly op4Decay: { readonly id: 26; readonly default: 0.3; readonly min: 0.005; readonly max: 2; readonly step: 0.005; readonly unit: "seconds"; };
  readonly op4Sustain: { readonly id: 27; readonly default: 0.5; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly op4Release: { readonly id: 28; readonly default: 0.2; readonly min: 0.005; readonly max: 3; readonly step: 0.005; readonly unit: "seconds"; };
  readonly chorusMix: { readonly id: 29; readonly default: 0; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly chorusRate: { readonly id: 30; readonly default: 0.6; readonly min: 0.05; readonly max: 6; readonly step: 0.01; readonly unit: "Hz"; };
  readonly chorusDepth: { readonly id: 31; readonly default: 3; readonly min: 0; readonly max: 12; readonly step: 0.1; readonly unit: "milliseconds"; };
  readonly delayMix: { readonly id: 32; readonly default: 0; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly delayTime: { readonly id: 33; readonly default: 0.25; readonly min: 0.02; readonly max: 1; readonly step: 0.005; readonly unit: "seconds"; };
  readonly delayFeedback: { readonly id: 34; readonly default: 0.35; readonly min: 0; readonly max: 0.92; readonly step: 0.01; readonly unit: "ratio"; };
  readonly delayTone: { readonly id: 35; readonly default: 3200; readonly min: 400; readonly max: 16000; readonly step: 100; readonly unit: "Hz"; };
  readonly reverbMix: { readonly id: 36; readonly default: 0; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly reverbSize: { readonly id: 37; readonly default: 0.6; readonly min: 0; readonly max: 1; readonly step: 0.01; readonly unit: "ratio"; };
  readonly reverbDamp: { readonly id: 38; readonly default: 4200; readonly min: 800; readonly max: 14000; readonly step: 100; readonly unit: "Hz"; };
  readonly reverbPredelay: { readonly id: 39; readonly default: 18; readonly min: 0; readonly max: 100; readonly step: 1; readonly unit: "milliseconds"; };
};

/** Patch parameter names accepted by `Engine.setParam`. */
export type ParamName = keyof typeof PARAMETERS;

export declare const PARAM: {
  readonly [Name in ParamName]: (typeof PARAMETERS)[Name]["id"];
};

export declare const PARAM_DEFAULTS: {
  readonly [Name in ParamName]: (typeof PARAMETERS)[Name]["default"];
};
